name:                fuddle
version:             0.19.1.0
github:              "whatsupfudd/fuddle-lang"
license:             BSD3
author:              "Hugo DesRosiers"
maintainer:          "hugo.desrosiers@boardingcities.com"
copyright:           "None."

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            software.

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/whatsupfudd/fuddle-lang#readme>

dependencies:
  - aeson
  - base >= 4.7 && < 5
  - bytestring
  - directory
  - text
  - time
  - vector
  # For YAML (config file):
  - yaml
  - directory
  - filepath
  # For Git (version):
  - gitrev
  # For options:
  - optparse-applicative
  # For Cont(T):
  - mtl
  # For elm-wasm:
  - ansi-wl-pprint
  - ansi-terminal >= 0.8
  - binary
  - containers
  - edit-distance
  - file-embed
  - filelock
  - fsnotify
  - ghc-prim
  - haskeline
  - HTTP
  - http-client
  - http-client-tls
  - http-types
  - language-glsl
  - mtl
  - network
  - parsec
  - process
  - raw-strings-qq
  - scientific
  - SHA
  - snap-core
  - snap-server
  - template-haskell
  - time
  - unordered-containers
  - utf8-string
  - websockets
  - word8
  - zip-archive

default-extensions:
  - OverloadedStrings
  - DuplicateRecordFields
  - OverloadedRecordDot
  # For ElmWasm?
  - TemplateHaskell

ghc-options:
# - -Wall
# - -Wunused-matches
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
#- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs:
    - src
    - elm-wasm/compiler/src
    - elm-wasm/terminal/src
    - elm-wasm/terminal/impl
    - elm-wasm/builder/src
    - elm-wasm/reactor/src

executables:
  fuddle:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - fuddle

tests:
  fuddle-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - fuddle
